name: Auto-accept repository invites

on:
  schedule:
    - cron: 55 * * * *
  workflow_dispatch:

jobs:
  accept:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-accept repository invites
        uses: kbrashears5/github-action-auto-accept-collabs@1.0.1
        with:
          TOKEN: ${{ secrets.GH_TOKEN }}